// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CreateTripController from "./create_trip_controller"
application.register("create-trip", CreateTripController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LikesController from "./likes_controller"
application.register("likes", LikesController)

import MapController from "./map_controller"
application.register("map", MapController)
