// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddMethodController from "./add_method_controller"
application.register("add-method", AddMethodController)

import CreateTripController from "./create_trip_controller"
application.register("create-trip", CreateTripController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LikesController from "./likes_controller"
application.register("likes", LikesController)

import RevealFormController from "./reveal_form_controller"
application.register("reveal-form", RevealFormController)
