meta_product_name: "Travel Plan"
meta_title: "Travel Plan - Make your dreams come true."
meta_description: "View other people vacations and find inspirations for your next trip."
meta_image: "logo.png" # should exist in `app/assets/images/`
